mysite/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.static import serve
# from django.urls import
from django.contrib import admin

from django.conf import settings

urlpatterns = [

    # path(r'^student/',)
    #

    url(r'^admin/', admin.site.urls),
    url(r'^student/', include('student.urls')),
    url(r'^faculty/', include('student.f_urls')),

    url(r'^accounts/',include('django.contrib.auth.urls')),

    # url(r'^student/searchs/', include('student.urls')),

    url(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),

    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}),



]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG==True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elif getattr(settings, 'FORCE_SERVE_STATIC', False):
    settings.DEBUG = True
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    settings.DEBUG = False

#
# if settings.DEBUG==False:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from django.contrib import admin

from django.conf.urls import url

from django.contrib.auth.views import LoginView
from . import views
from .models import Student
app_name='student'

urlpatterns= [
    #homepage

# url(r'^up/$',views.simple_upload,name='s'),

# url(r'^csv/$',views.upform,name='a'),

    # url(r'^regno-autocomplete/$',views.RegisterNumberAutoComplete.as_view(model=Student),name='regno-autocomplete'),
    # url(r'',views.LoginUserView.as_view(), name='login_new'),
    url(r'^a/$',views.t,name="test_pdf"),

    url(r'^email/$',views.email,name=""),

    url(r'^attendence_search/$',views.attendence_search,name="attendence_search"),

    # url(r'^sms/$',views.sms,name=""),

    url(r'^pdf/$',views.render_to_pdf,name='pdf_render'),
   
    url(r'^student_detail/$',views.studentdetail_search,name='student_detail'),

    url(r'^test/$',views.studentdetail_search,name='student_detail'),

    url(r'^public_form/$',views.search_form,name='public_marks_search'),

    url(r'^mark_pdf_form/$',views.pdf_form,name='pdf_form'),

    url(r'^report/(?P<regno>[0-9]+)/(?P<branch>[A-Z]+)/(?P<cursem>[0-8])/$',views.student_report,name='student_report'),

    url(r'^pa/',views.load_subject_code,name='subject_list'),

    url(r'^subname/',views.load_subject_name,name='subject_name'),

    url(r'^subname2/', views.load_subject_name2, name='subject_name2'),

    url(r'^login/$', LoginView.as_view(), name='login'),


    url(r'^addcsv/$', views.StudentCsv, name='student_addcsv'),

    url(r'^attendence_add/$',views.AttendenceCsv, name='attendence_csv'),

    url(r'^user_add/$',views.UserCsv,name='user_csv'),

    # url(r'^logtest/$',views.LoginUser.as_view(),name='testlog'),

    # url(r'^contact/$',views.ContactFormView1, name='submit'),

# url(r'^edits/$',views.Studentform_edit,name='s'),
    url(r'^mark_search/$',views.Marklistsearch,name='marklist_search'),

    url(r'^edit_marks/$',views.marklist_search,name="edit_marks"),

     url(r'^marks_search/$',views.searchmarks,name='ss'),

   url(r'^edits/(?P<regno>[0-9]+)/$',views.Studentform_edit,name='s'), # // okay working well

# url(r'^edits/(?P<branch>[A-Z]+)/$',views.Studentform_edit,name='s'),

# url(r'^edits/(?P<branch>[A-Z]+)/(?P<join>[0-9]+)/(?P<cursem>[0-8])/(?P<type>[A-Za-z]+)$',views.Studentform_edit,name='s'),

    url(r'^login_user/$',views.loguser,name='new_log'),

    url(r'^$', views.testing, name='index2'),

     url(r'^sss$', views.Indexview.as_view(), name='index'),

     url(r'^logout/$',views.logoutuser,name='logout'),



     url(r'^home/$',views.home,name='home'),

    #student/regno

    # for generic view DetailView url(r'^(?P<regno>[0-9]+)/$', views.Detailview.as_view(), name='detail'),
     # url(r'^(?P<regno>[0-9]+)/$', views.detail, name='detail'),

    #call form to add student url pattern
     # url(r'^add/$', views.Studentcreate.as_view(),name='student_add'),

    url(r'^add/$', views.StudentCreate,name='student_add'),

      url(r'^view/(?P<regno>[0-9]+)/$',views.detail,name='views'),

      #call form to update and view data the detail url
     # url(r'^edit/(?P<pk>[0-9]+)/$', views.Studentupdate.as_view(),name='detail'),

    url(r'^edit/(?P<pk>[0-9]+)/$', views.StudentUpdate,name='detail'),

      # url(r'edit/(?P<pk>[0-9]+)(?P<branch>[a-z]+)/',views.Studentupdate.as_view(),name='details')

   # url(r'^edits/(?P<pk>[0-9]+)/delete/$', views.Studentdelete.as_view(), name='delete'),

       url(r'^delete/(?P<pk>[0-9]+)/$', views.Studentdelete.as_view(), name='delete'),

     url(r'^search_form/$',views.Studentsearch,name='searchform'),

       url(r'^search/$',views.searchs,name='search'),

    #added this for making detailview generic view

     # url(r'^view/(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='view'),

     #register user to login
     url(r'^register/$',views.UserFormView.as_view(),name='register'),

    url(r'^register1/$',views.Studentform,name='aaaa'),


    url(r'^test/$',views.testing,name='test'),

    url(r'^stu_search/$',views.student_search,name='student_search'),




    # for faculty
    url(r'^fac_search/$',views.faculty_search,name='faculty_search'),

    url(r'^faculty/$',views.Facultyview.as_view(),name='faculty_show'),


    url(r'^faculty_details/(?P<pk>[0-9]+)/$',views.FacultyDetail,name='faculty_details'),


    url(r'^faculty_add/$',views.FacultyCreate,name='faculty_add'),

    #for update view pk should be the name passed as arguments
    url(r'^faculty_edit/(?P<pk>[0-9]+)/$', views.Facultyupdate, name='faculty_edit'),

    url(r'^faculty_delete/(?P<pk>[0-9]+)/$', views.Facultydelete.as_view(), name='faculty_delete'),

    url(r'^facultysubject_search/$', views.facultysubject_search, name='facultysubject_search'),




  #subject
    url(r'^list_subjects/$',views.SubjectsList,name='subjects_list'),

    url(r'^faculty_addsubmap/$',views.FacultySubMapCreate,name='faculty_addsubmap'),

    # url(r'^faculty_editsubmap/(?P<id>[0-9]+)/$',views.FacultySubMapEdit.as_view(),name='faculty_editsubmap'),



  #marklist
    # url(r'^marklist_add/$'views.MarklistCreate.as_view(),name='marklist_add'),


url(r'^marklist_add/$',views.MarklistCreate,name='marklist_add'),

    url(r'^marklist_edit/(?P<regno>[0-9]+)/(?P<branch>[A-Z]+)/(?P<cursem>[0-9]+)/(?P<section>[A-B]+)/(?P<type>[A-Za-z]+)/$', views.MarklistUpdate, name='marklist_edit'),

    url(r'^marklist_csv',views.MarklistCsv,name="marklist_csv"),

    url(r'^attendence_edit/(?P<regno>[0-9]+)/(?P<cursem>[0-9]+)/(?P<section>[A-B]+)/(?P<id>[0-9]+)',
        views.AttendenceUpdate, name='attendence_edit'),

#
url(r'^attendence_calc/(?P<regno>[0-9]+)/(?P<section>[A-B]+)/(?P<cursem>[0-9]+)/(?P<id>[0-9]+)',
        views.attendence_calc, name='attendence_calc'),

    #subject_profile

    # url(r'^subject_add/$',views.Subject_ProfileCreate.as_view(),name='subject_add'),

    # url(r'^subject_edit/(?P<pk>[A-Z]+[_]+[0-9]+)/$', views.Subject_ProfileEdit.as_view(), name='subject_edit'),

  #subject_profile

    url(r'^subject_add/$',views.Subject_ProfileCreate,name='subject_add'),

    url(r'^subject_edit/(?P<pk>[A-Z]+[_]+[0-9]+)/$', views.Subject_ProfileEdit.as_view(), name='subject_edit'),


    #for syllabus
    # url(r'^syllabus_add/$',views.SyllabusCreate.as_view(),name='syllabus_add'),

    url(r'^syllabus_add/$',views.SyllabusCreate,name='syllabus_add'),

    url(r'^syllabus_edit/(?P<pk>[0-9]+)/$', views.SyllabusEdit, name='syllabus_edit'),

    url(r'^syllabus_search/$',views.syllabus_search,name='syllabus_search'),


     url(r'^subjectprofile_view/(?P<id>[0-9]+)/$',views.subjectprofileview,name='subjectprofile_list'),


     url(r'^subjectprofile_edit/(?P<id>[0-9]+)$',views.subjectprofileedit,name='subjectprofile_edit'),

    url(r'^regnoroll/$',views.RollnoRegnoMapAdd,name='regno_map'),


    url(r'^attendence_pdf_search/$',views.attendence_pdf,name='attendence_pdf_search'),

    url(r'^attendence_list/$',views.attendence_list_pdf,name='attendence_list'),

    url(r'^attendence_search/$',views.attendence_search,name='attendence_search'),

    # url(r'^attendence_edit/(?P<year>[0-9]+)/(?P<branch>[A-Z]+)/(?P<cursem>[0-9]+)/(?P<section>[A-B]+)',views.attendenceedit,name='attendence_edit'),



    # user.year/user.branch/user.cursem/user.section

    #
    # url(r'^regnoroll/(?P<pk>[0-9]+)/$', views.RollnoRegnoMapEdit.as_view(), ),
    #
    # url(r'^facultymap/$',views.StudentFacultyLabMapAdd,),
    #
    # url(r'^facultymap/(?P<pk>[0-9]+)/$',views.StudentFacultyLabMapEdit.as_view(),),
    # #
    # url(r'student_login/',views.student_login),



]

student/templates/student/csv.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload CSV for Students</title>
    <meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
        {% load static %}
		<link rel="stylesheet" href="{% static 'student/assets/css/main.css' %}" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
</head>
<body>


{% block content %}
  <form action="/student/up/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
{% endblock %}


</body>
</html>

student/templates/student/indexcard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

student/templates/student/studentcsv.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload CSV For Student Indexcard </title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes"/>
    <!--[if lte IE 8]>
    <script src="assets/js/ie/html5shiv.js"></script><![endif]-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'student/assets/css/main.css' %}"/>
    <!--[if lte IE 9]>
    <link rel="stylesheet" href="assets/css/ie9.css"/><![endif]-->
    <!--[if lte IE 8]>
    <link rel="stylesheet" href="assets/css/ie8.css"/><![endif]-->
</head>
<body>

<!-- Wrapper -->
<div id="wrapper">

    <!-- Main -->
    <div id="main">
        <div class="inner">
            <header id="header">
                <div class="12u 12u$(small)">
                    <a href="cusat.ac.in" class="logo"
                       style="padding-top:10px;font-size:30px;"><strong>CUSAT</strong></a>
                    <weak style="font-size:40px;float:right"> School of Engineering</weak>
                    </a></br>
                    <ul class="icons">
                        <div class="box alt">
                            <!--<div class="row 50% uniform">-->

                                <!--{% load staticfiles %}-->
                                <!--<div class="3u$"><span class="image Small" style="float:left"><img-->
                                        <!--src="{%  static 'student/images/pic01.jpg'%}"/></span></div>-->
                            <!--</div>-->
                            <div class="u u$(small)">
                                  {% if user.is_authenticated %}
                                              <p3 style="float:right"><h3>Hello {{ request.user.username }}</h3></p3>
                                        {% endif %}
                            </div>
                        </div>
                    </ul>
                </div>
            </header>


            <section style="margin-left:75px">

                <h3>Note : CSV file should have the fields in the format given below:</h3>
                <ul>
                       regno, name, branch, cursem, join, section, status, parent, admtype, gender, admissionno, permanentaddress, temporaryaddress, dateofbirth, category, emailid, personwithdisabilities, catrank, religion, bloodgroup, parentorguardianname, parentorguardianoccupation, parentorguardiancontactno, parentorguardianemailid, miniproject, miniprojectguide, mainproject, mainprojectguide, behaviour, studentcontactno, studentemailid, tenboard, tenregisterno, tenmarks, tenpercentage, tenyear, qualifyingboard, qualifyingregisterno, qualifyingmarks, qualifyingpercentage,qualifyingyear,specialreservation
                </ul>
		<h3> Status field must given the exact value as given below:</h3> 		
		<ul>
			The status field should have the value 'Active' for Currently Studying students and 'Pass out' for those who have completed the course and 'Drop out' for those who have discontinued their studies.
		</ul>

		<h3>Optional fields</h3>
		<ul>
		   parentorguardianemailid,personwithdisabilities,miniproject,miniprojectguide,mainproject,
			mainprojectguide,specialreservation.  
		</ul>

                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
                    <button type="submit">Submit</button>

                </form>

            </section>

        </div>
    </div>
    <!-- Sidebar -->
     <div id="sidebar">
						<div class="inner">
							<!-- Menu -->
								<nav id="menu">
									<header class="major">
										<h2>Menu</h2>
									</header>
									<ul>
										<li><a href="{% url 'student:home' %}">Home</a></li>
                                        {% if user.username == 'admin' %}
                                        <li><a href="/admin">Admin</a> </li>
                                        {% endif %}
										<li>
											<span class="opener">Student</span>
											<ul>
												<li>
													<span class="opener"><b>IndexCard</b></span>
													<ul>
														<li><a href="{% url 'student:student_add' %}">Add </a></li>
														<li><a href="{% url 'student:student_search' %}">Edit/View</a></li>
														<li><a href="{% url 'student:student_addcsv'%}">Upload CSV</a> </li>

													</ul>
												</li>
												<li>
													<span class="opener"><b>Marklist</b></span>
													<ul>
														<li><a href="{% url 'student:marklist_add' %}">Add </a></li>
														<li><a href="{% url 'student:edit_marks'%}">Edit</a> </li>
														<li><a href="{% url 'student:marklist_search' %}">View</a></li>

													</ul>
												</li>
												<li>
													<span class="opener"><b>Attendence</b></span>
													<ul>
														<!--<li><a href="{% url 'student:regno_map' %}">Add</a></li>-->
														<li><a href="{% url 'student:attendence_csv'%}">Add as CSV</a></li>
														<li><a href="{% url 'student:attendence_search' %}">Edit/View</a></li>
													</ul>
												</li>

											</ul>
										</li>

										<li>
												<span class="opener">Syllabus</span>
												<ul>
													<li>
														<span class="opener"><b>SyllabusProfile</b></span>
														<ul>
															<li><a href="{% url 'student:syllabus_add' %}">Add </a></li>
															<li><a href="{% url 'student:syllabus_search' %}">Edit/View</a></li>

														</ul>

													</li>

													<li>
														<span class="opener"><b>Subjects</b></span>
														<ul>
															<li><a href="{% url 'student:subject_add'%}">Add subject</a></li>
                                                            <li><a href="{% url 'student:syllabus_search' %}">Edit/View subject </a></li>
														</ul>
													</li>

												</ul>
											</li>

										<li>
											<span class="opener">Faculty</span>
											<ul>
												<li>
													<span class="opener"><b>Faculty Profile</b></span>
													<ul>
														<li><a href="{% url 'student:faculty_add' %}">Add </a></li>
														<li><a href="{% url 'student:faculty_search' %}">Edit/View</a></li>
													</ul>
												</li>
												<li>
													<span class="opener"><b>Faculty Subject Map</b></span>
													<ul>
														<li><a href="{% url 'student:faculty_addsubmap' %}">Add </a></li>
														<li><a href="{% url 'student:facultysubject_search' %}">Edit/View</a></li>
													</ul>
												</li>

											</ul>
										</li>

                                        {% if user.username == 'admin' %}
												<li><a href="{% url 'student:register'%}">Register User</a></li>
												<li><a href="{% url 'student:user_csv' %}">Upload Users</a></li>
																				<!--<li><a href="{% url 'student:student_detail'%}">SEarch stude</a></li>-->

                                        {% endif %}
                                        {% if user.is_authenticated == False %}
                                        <li><a href="{% url 'student:login' %}">Login</a></li>
                                        {% endif %}
                                        {% block content %}
                                        {% if user.is_authenticated %}
{#                                             {% print(user.is_authenticated) %}#}
										<li><a href="/accounts/password_reset/">Change Password</a></li>
                                            <li><a href="{% url 'student:logout' %}">Logout</a></li>

                                        {% endif %}
                                    {% endblock %}
                                    </ul>
										</li>
									</ul>
								</nav>

							<!-- Section -->
								<section>
									<header class="major">
										<h2>Get in touch</h2>
									</header>
									<p>School of Engineering PTA</p>
									<ul class="contact">
										<li class="fa-envelope-o"><a href="#">principal_soe@cusat.ac.in</a></li>
										<li class="fa-phone">0484-2556187</li>
										<li class="fa-home">School of Engineering, CUSAT<br />
										Thrikkakara, Kochi-21</li>
									</ul>
								</section>
						</div>
					</div>
</div>
<!-- Footer -->
<footer id="footer">
    <p class="copyright" style="float:center"> &nbsp&nbsp&nbsp&nbsp&nbsp <i> &copy; 2018. Div of Computer Science,School
        of Engieering,CUSAT. All rights reserved.</i></p>
</footer>

</div>

</div>

<!-- Scripts -->
{% load static %}
<script src="{% static 'student/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'student/assets/js/skel.min.js' %}"></script>
<script src="{% static 'student/assets/js/util.js' %}"></script>
<script src="{% static 'student/assets/js/main.js' %}"></script>

</body>


</html>

student/templates/student/syllabus_list.html
<!DOCTYPE HTML>
<!--
	Editorial by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>{{title}}</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes"/>
    <!--[if lte IE 8]>
    <script src="assets/js/ie/html5shiv.js"></script><![endif]-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'student/assets/css/main.css' %}"/>
    <!--[if lte IE 9]>
    <link rel="stylesheet" href="assets/css/ie9.css"/><![endif]-->
    <!--[if lte IE 8]>
    <link rel="stylesheet" href="assets/css/ie8.css"/><![endif]-->
</head>
<body>

<!-- Wrapper -->
<div id="wrapper">

    <!-- Main -->
    <div id="main">
        <div class="inner">
            <header id="header">
                <div class="12u 12u$(small)">
                    <a href="cusat.ac.in" class="logo"
                       style="padding-top:10px;font-size:30px;"><strong>CUSAT</strong></a>
                    <div style="font-size:40px;float:right"> School of Engineering</div>
                    </a></br>
                    <ul class="icons">
                        <div class="box alt">
                            <!--<div class="row 50% uniform">-->
                                <!--{% load staticfiles %}-->
                                <!--<div class="3u$"><span class="image Small" style="float:left"><img-->
                                        <!--src="{% static 'student/images/pic01.jpg' %}"/></span></div>-->
                            <!--</div>-->
                            <div class="u u$(small)">
                                 {% if user.is_authenticated %}
                                              <p3 style="float:right"><h3>Hello {{ request.user.username }}</h3></p3>
                                        {% endif %}
                            </div>
                        </div>

                    </ul>
                </div>
            </header>
        </div>
        {% block form %}

        <!--Body-->
        <section>
            <div style="text-align: center;margin-left: 250px; " class="4u 12u$(medium)">
                <form method="get">
                    <table style="width:300px;">
                    <tr>
                        <th style="text-align:center;">

                            <label style="font-size: medium;font-family:Arial">{{filter.form.year.label}}</label>
                        </th>
                    </tr>
                    <tr>
                        <td>
                            {{filter.form.year}}
                        </td>
                    </tr>
                </table>
                    <button type="submit" name="submit" style="margin-left:5px;">Search</button>
                </form>

            </div>




            {% if request.GET %}
            <ul style="margin-left:250px">
                {% for user in filter.qs %}
                <p><a href="{% url 'student:syllabus_edit' user.pk %}">{{ user.year }} - {{ user.dept }}</a>
                    &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'student:subjectprofile_list' user.pk %}">View Subjects</a>
                    &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'student:subjectprofile_edit' user.pk %}">Edit Subjects</a>
                </p>


                {% empty %}
                <p style="font-weight: bold">Sorry no data found with the given filter </p>
                {% endfor %}
            </ul>
            {% endif %}


            {% if students.has_other_pages %}
            <ul class="pagination">
                {% if students.has_previous %}
                <li><a href="?page={{ students.previous_page_number }}">&laquo;</a></li>
                {% else %}
                <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in students.paginator.page_range %}
                {% if students.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if students.has_next %}
                <li><a href="?page={{ students.next_page_number }}">&raquo;</a></li>
                {% else %}
                <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
            {% endif %}

        </section>
        {% endblock %}
    </div>
    <!-- Sidebar -->
    <div id="sidebar">
						<div class="inner">
							<!-- Menu -->
								<nav id="menu">
									<header class="major">
										<h2>Menu</h2>
									</header>
									<ul>
										<li><a href="{% url 'student:home' %}">Home</a></li>
                                        {% if user.username == 'admin' %}
                                        <li><a href="/admin">Admin</a> </li>
                                        {% endif %}
										<li>
											<span class="opener">Student</span>
											<ul>
												<li>
													<span class="opener"><b>IndexCard</b></span>
													<ul>
														<li><a href="{% url 'student:student_add' %}">Add </a></li>
														<li><a href="{% url 'student:student_search' %}">Edit/View</a></li>
														<li><a href="{% url 'student:student_addcsv'%}">Upload CSV</a> </li>

													</ul>
												</li>
												<li>
													<span class="opener"><b>Marklist</b></span>
													<ul>
														<li><a href="{% url 'student:marklist_add' %}">Add </a></li>
														<li><a href="{% url 'student:edit_marks'%}">Edit</a> </li>
														<li><a href="{% url 'student:marklist_search' %}">View</a></li>

													</ul>
												</li>
												<li>
													<span class="opener"><b>Attendence</b></span>
													<ul>
														<!--<li><a href="{% url 'student:regno_map' %}">Add</a></li>-->
														<li><a href="{% url 'student:attendence_csv'%}">Add as CSV</a></li>
														<li><a href="{% url 'student:attendence_search' %}">Edit/View</a></li>
													</ul>
												</li>

											</ul>
										</li>

										<li>
												<span class="opener">Syllabus</span>
												<ul>
													<li>
														<span class="opener"><b>SyllabusProfile</b></span>
														<ul>
															<li><a href="{% url 'student:syllabus_add' %}">Add </a></li>
															<li><a href="{% url 'student:syllabus_search' %}">Edit/View</a></li>

														</ul>

													</li>

													<li>
														<span class="opener"><b>Subjects</b></span>
														<ul>
															<li><a href="{% url 'student:subject_add'%}">Add subject</a></li>
                                                            <li><a href="{% url 'student:syllabus_search' %}">Edit/View subject </a></li>
														</ul>
													</li>

												</ul>
											</li>

										<li>
											<span class="opener">Faculty</span>
											<ul>
												<li>
													<span class="opener"><b>Faculty Profile</b></span>
													<ul>
														<li><a href="{% url 'student:faculty_add' %}">Add </a></li>
														<li><a href="{% url 'student:faculty_search' %}">Edit/View</a></li>
													</ul>
												</li>
												<li>
													<span class="opener"><b>Faculty Subject Map</b></span>
													<ul>
														<li><a href="{% url 'student:faculty_addsubmap' %}">Add </a></li>
														<li><a href="{% url 'student:facultysubject_search' %}">Edit/View</a></li>
													</ul>
												</li>

											</ul>
										</li>

                                        {% if user.username == 'admin' %}
												<li><a href="{% url 'student:register'%}">Register User</a></li>
												<li><a href="{% url 'student:user_csv' %}">Upload Users</a></li>
																				<!--<li><a href="{% url 'student:student_detail'%}">SEarch stude</a></li>-->

                                        {% endif %}
                                        {% if user.is_authenticated == False %}
                                        <li><a href="{% url 'student:login' %}">Login</a></li>
                                        {% endif %}
                                        {% block content %}
                                        {% if user.is_authenticated %}
{#                                             {% print(user.is_authenticated) %}#}
										<li><a href="/accounts/password_reset/">Change Password</a></li>
                                            <li><a href="{% url 'student:logout' %}">Logout</a></li>

                                        {% endif %}
                                    {% endblock %}
                                    </ul>
										</li>
									</ul>
								</nav>

							<!-- Section -->
								<section>
									<header class="major">
										<h2>Get in touch</h2>
									</header>
									<p>School of Engineering PTA</p>
									<ul class="contact">
										<li class="fa-envelope-o"><a href="#">principal_soe@cusat.ac.in</a></li>
										<li class="fa-phone">0484-2556187</li>
										<li class="fa-home">School of Engineering, CUSAT<br />
										Thrikkakara, Kochi-21</li>
									</ul>
								</section>
						</div>
					</div>
</div>
<!-- Footer -->
<footer id="footer">
    <p class="copyright" style="float:right"> &nbsp&nbsp&nbsp&nbsp&nbsp <i> &copy; 2018. Div of Computer Science,School
        of Engieering,CUSAT. All rights reserved.</i></p>
</footer>

</div>

</div>

<!-- Scripts -->
{% load staticfiles %}
<script src="{% static 'student/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'student/assets/js/skel.min.js' %}"></script>
<script src="{% static 'student/assets/js/util.js' %}"></script>
<script src="{% static 'student/assets/js/main.js' %}"></script>


</body>
</html>